server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    suffix: .html
  redis:
    host: 127.0.0.1


mybatis:
  type-aliases-package: com.example.domain
  configuration:
    map-underscore-to-camel-case: true



